apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: tzpay
type: Opaque
data:
  wallet-esk: ""
  wallet-pass: ""
  twitter-consumer-key: ""
  twitter-consumer-secret: ""
  twitter-access-token: ""
  twitter-access-secret: ""
  twilio-account-sid: ""
  twilio-auth-token: ""
  twilio-from: ""
  twilio-to: ""